spring:
  application:
    name: asset-management-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/asset_management
    username: postgres
    password: Vamsi!1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  security:
    jwt:
      secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
      expiration: 86400000 # 24 hours

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.assetmanagement: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN